### ISSUE TITLE
Looking for some direction re: speed....

### ISSUE THREAD

**Issue by weisisheng** [ai-ng/magic-spell#1]
Question from the cheap seats--

Trying this example embedded in another MVP example, response times are 10x-20x more than if I use the console directly, or an AWS lambda managing access to the api.

Would appreciate any tips, tricks, etc.

*** removed rate limiting while testing...

**Comment by n1ckoates** [comment]
What region are you running the function in? Groq's servers are only in San Francisco right now, so if you're running it outside of there you'll see increased latency. The function is pinned to SFO1 on Vercel via `vercel.json`, but if you're on a different provider you'll have to configure it yourself.

**Comment by n1ckoates** [comment]
Closing this, feel free to re-open if you're still running into this issue!
